apiVersion: apps/v1
kind: Deployment
metadata:
  name: cozserver-deployment
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: cozserver
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cozserver
    spec:
      containers:
      - name: cozserver
        image: sebcontents/cozserver:3.0 # 3.0 version
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1       

# initialDelaySeconds: Number of seconds after the container has started before liveness or readiness probes are initiated. Defaults to 0 seconds. Minimum value is 0.
# periodSeconds: How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.

