apiVersion: apps/v1
kind: Deployment
metadata:
  name: cozserver-deployment
spec:
  selector:
    matchLabels:
      app: cozserver
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: cozserver
    spec:
      containers:
      - name: cozserver
        image: sebcontents/cozserver:1.0
        ports:
        - containerPort: 80
