version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverlessphoto"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13zgp5dlff5uo"
s3_prefix = "serverlessphoto"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
