# docker compose 파일을 완성하고
# http://localhost로 접속했을 때 서버로부터 온 메시지가 표시되게 만드세요
version: "3.0"

services:
  nginx:
    build: frontend
    restart: 'always'
    ports:
      - "80:80"
    depends_on:
      - node
    container_name: frontend

  node:
    build: backend
    restart: 'always'
    ports:
      - "3333:80"
    container_name: backend
